#spring.application.name=Traineeship Management Application

#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/traineeship_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=minkoitas

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# Removed schema-generation script properties to let Hibernate execute DDL directly:
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=traineeship.sql
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-source=metadata
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
